{
    "title": "In Django 3.2 before 3.2.16, 4.0 before 4.0.8, and 4.1 before 4.1.2, internationalized URLs were subject to a potential denial of service attack via the locale parameter, which is treated as a regular expression.",
    "score": 7.5,
    "severity": "HIGH",
    "cwe_id": "NVD-CWE-Other",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "technique_id": "T1087",
            "confidence": "5.7",
            "technique_name": "Account Discovery"
        },
        {
            "technique_id": "T1222",
            "confidence": "3.1",
            "technique_name": "File and Directory Permissions Modification"
        },
        {
            "technique_id": "T1543",
            "confidence": "25.5",
            "technique_name": "Create or Modify System Process"
        }
    ]
}
