{
    "title": "python-ldap before 3.4.0 is vulnerable to a denial of service when ldap.schema is used for untrusted schema definitions, because of a regular expression denial of service (ReDoS) flaw in the LDAP schema parser. By sending crafted regex input, a remote authenticated attacker could exploit this vulnerability to cause a denial of service condition.",
    "score": 6.5,
    "severity": "MEDIUM",
    "cwe_id": "NVD-CWE-Other",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:a:python-ldap:python-ldap:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1059",
            "confidence": "70.0",
            "techniqueName": "Command and Scripting Interpreter"
        },
        {
            "techniqueId": "T1543",
            "confidence": "12.6",
            "techniqueName": "Create or Modify System Process"
        }
    ]
}
