{
    "title": "An issue was discovered in the Linux kernel through 4.17.10. There is an out-of-bounds access in __remove_dirty_segment() in fs/f2fs/segment.c when mounting an f2fs image.",
    "score": 5.5,
    "severity": "MEDIUM",
    "cwe_id": "CWE-476",
    "cvss_vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "technique_id": "T1057",
            "confidence": "3.9",
            "technique_name": "Process Discovery"
        },
        {
            "technique_id": "T1059",
            "confidence": "3.0",
            "technique_name": "Command and Scripting Interpreter"
        },
        {
            "technique_id": "T1087",
            "confidence": "10.7",
            "technique_name": "Account Discovery"
        },
        {
            "technique_id": "T1213",
            "confidence": "3.6",
            "technique_name": "Data from Information Repositories"
        },
        {
            "technique_id": "T1548.003",
            "confidence": "2.0",
            "technique_name": "Sudo and Sudo Caching"
        }
    ]
}
