{
    "title": "Unspecified vulnerability in db2jds in IBM DB2 8.1 before FP18 allows remote attackers to cause a denial of service (service crash) via malicious packets.",
    "score": 5.0,
    "severity": "MEDIUM",
    "cwe_id": "NVD-CWE-noinfo",
    "cvss_vector": "CVSS:2.0/AV:N/AC:L/Au:N/C:N/I:N/A:P",
    "cpe_match": [
        "cpe:2.3:a:ibm:db2:8.1:fp1:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp10:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp6c:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp2:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:*:fp17:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp5:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp8:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp8a:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp14:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp11:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp13:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp9a:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp4a:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp12:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp17a:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp9:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp15:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp3:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp7a:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp6a:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp6b:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp7:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp6:*:*:*:*:*:*",
        "cpe:2.3:a:ibm:db2:8.1:fp4:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1498",
            "techniqueName": "Network Denial of Service",
            "confidence": "46.5"
        },
        {
            "techniqueId": "T1499",
            "techniqueName": "Endpoint Denial of Service",
            "confidence": "49.8"
        }
    ]
}
