{
    "title": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the getpeername function having an ENOTCONN error, a different vulnerability than CVE-2010-3494.",
    "score": 4.3,
    "severity": "MEDIUM",
    "cwe_id": "CWE-362",
    "cvss_vector": "CVSS:2.0/AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "cpe_match": [
        "cpe:2.3:a:g.rodola:pyftpdlib:0.5.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.4.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.2.0:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:0.3.0:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1068",
            "techniqueName": "Exploitation for Privilege Escalation",
            "confidence": "4.5"
        },
        {
            "techniqueId": "T1498",
            "techniqueName": "Network Denial of Service",
            "confidence": "27.7"
        },
        {
            "techniqueId": "T1499",
            "techniqueName": "Endpoint Denial of Service",
            "confidence": "29.7"
        },
        {
            "techniqueId": "T1548",
            "techniqueName": "Abuse Elevation Control Mechanism",
            "confidence": "2.8"
        },
        {
            "techniqueId": "T1554",
            "techniqueName": "Compromise Client Software Binary",
            "confidence": "2.2"
        }
    ]
}
