{
    "title": "The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isnt given via proxy_config) doesnt verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.",
    "score": 6.5,
    "severity": "MEDIUM",
    "cwe_id": "CWE-295",
    "cvss_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N",
    "cpe_match": [
        "cpe:2.3:a:python:urllib3:*:*:*:*:*:*:*:*",
        "cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*",
        "cpe:2.3:a:oracle:peoplesoft_enterprise_peopletools:8.59:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1059",
            "confidence": "77.2",
            "techniqueName": "Command and Scripting Interpreter"
        }
    ]
}
