{
    "title": "An out-of-bounds read flaw was found in the Linux kernel\u2019s io_uring module in the way a user triggers the io_read() function with some special parameters. This flaw allows a local user to read some memory out of bounds.",
    "score": 6.1,
    "severity": "MEDIUM",
    "cwe_id": "CWE-125",
    "cvss_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:H",
    "cpe_match": [
        "cpe:2.3:o:linux:linux_kernel:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1033",
            "confidence": "2.1",
            "techniqueName": "System Owner/User Discovery"
        },
        {
            "techniqueId": "T1057",
            "confidence": "2.8",
            "techniqueName": "Process Discovery"
        },
        {
            "techniqueId": "T1087",
            "confidence": "4.0",
            "techniqueName": "Account Discovery"
        },
        {
            "techniqueId": "T1123",
            "confidence": "2.7",
            "techniqueName": "Audio Capture"
        },
        {
            "techniqueId": "T1213",
            "confidence": "3.0",
            "techniqueName": "Data from Information Repositories"
        }
    ]
}
