{
    "title": "The ftp_STOU function in FTPServer.py in pyftpdlib before 0.2.0 does not limit the number of attempts to discover a unique filename, which might allow remote authenticated users to cause a denial of service via a STOU command.",
    "score": 4.0,
    "severity": "MEDIUM",
    "cwe_id": "CWE-264",
    "cvss_vector": "CVSS:2.0/AV:N/AC:L/Au:S/C:N/I:N/A:P",
    "cpe_match": [
        "cpe:2.3:a:g.rodola:pyftpdlib:0.1:*:*:*:*:*:*:*",
        "cpe:2.3:a:g.rodola:pyftpdlib:*:*:*:*:*:*:*:*"
    ],
    "cve_source": [
        "NVD"
    ],
    "ttpMapping": [
        {
            "techniqueId": "T1489",
            "techniqueName": "Service Stop",
            "confidence": "2.8"
        },
        {
            "techniqueId": "T1498",
            "techniqueName": "Network Denial of Service",
            "confidence": "4.8"
        },
        {
            "techniqueId": "T1499",
            "techniqueName": "Endpoint Denial of Service",
            "confidence": "5.1"
        }
    ]
}
